name: Deploy Preview to Cloud Run

on:
  pull_request:
    branches: [develop]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sanitize branch name
        id: sanitize
        run: |
          RAW_BRANCH="${{ github.head_ref }}"
          SANITIZED_BRANCH=$(echo "$RAW_BRANCH" | tr '/' '-' | tr -cd 'a-zA-Z0-9\-')
          echo "branch=$SANITIZED_BRANCH" >> $GITHUB_OUTPUT

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DEV_GCP_SA_KEY }}

      - name: Set gcloud project
        run: gcloud config set project $PROJECT_ID

      - name: Build Docker image
        run: |
          IMAGE_NAME=gcr.io/$PROJECT_ID/nextjs-preview-${{ steps.sanitize.outputs.branch }}
          docker build -t $IMAGE_NAME .
          gcloud auth configure-docker
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          SERVICE_NAME=preview-${{ steps.sanitize.outputs.branch }}
          IMAGE_NAME=gcr.io/$PROJECT_ID/nextjs-preview-${{ steps.sanitize.outputs.branch }}

          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_NAME \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --port 8080

      - name: Output Preview URL
        run: |
          echo "✅ Preview should be available at:"
          echo "https://preview-${{ steps.sanitize.outputs.branch }}-${PROJECT_ID//[!a-zA-Z0-9]/}-${REGION}.a.run.app"