
name: Deploy Preview to Cloud Run

on:
  pull_request:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.DEV_GCP_PROJECT_ID }}
      REGION: ${{ secrets.DEV_GCP_REGION }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DEV_GCP_SA_KEY }}

      - name: Set gcloud CLI project
        run: gcloud config set project $PROJECT_ID

      - name: Build and push Docker image
        run: |
          BRANCH=$(echo ${{ github.head_ref }} | tr '/' '-')
          IMAGE_NAME=gcr.io/$PROJECT_ID/nextjs-preview-$BRANCH
          docker build -t $IMAGE_NAME .
          gcloud auth configure-docker
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          SERVICE_NAME=preview-${{ github.head_ref }}
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/nextjs-preview-${{ github.head_ref }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --port 8080